env:
    token_telegram: "ENCRYPTED[ef57f747d32c7145cad73cba52ab20330068ae5dcc6510a4c762bbbbac14881a135bda5689f4dbe75a30c39c18a3b8a4]"
    id_telegram: "ENCRYPTED[6f7afb813a6757a3ff95e1a90557ae57b3aed00a6af9860d7616c94c3bf2b390dedc23c8075bcc4adb14b8f1933ce49c]"
    rclone_config: "ENCRYPTED[81f2ea42a1bb72f5514f01604e25bb9057eb0b6f1b0f5a18434dd7175df07619a880e75ecb9597e10e69fba44553fe84]"
    github: "ENCRYPTED[2965b5f80f1182edf1dd28807108e3a7c3103e75029f9d35fbae911fa02285085874a7c88fd9b36f457cd5b1274dba1c]"

task:
    name: nusantara
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    dummy_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
      - cd /tmp
      - git clone https://github.com/I-n-o-k/android_tools /tmp/anu
      - cd /tmp/anu
      - wget https://eunha.ovin.my.id/0:/Data/xiaomi.eu_multi_HMNote94G_HM9T_21.9.15_v12-11.zip
      - export GIT_TOKEN="$github"
      - ./tools/rom_extract.sh xiaomi.eu_multi_HMNote94G_HM9T_21.9.15_v12-11.zip
      - ./tools/dump_push.sh xiaomi.eu_multi_HMNote94G_HM9T_21.9.15_v12-11.zip
      - ./tools/dummy_dt.sh dumps/*
      - cd /tmp/anu
      - zip -r /tmp/dt.zip /tmp/anu/dummy_dt
      - rclone copy dt.zip inok: -P
